In [1]:
import numpy as np
import pandas as pd

In [2]:
filename = "../data/gold_standard_xml/BioQRator_annotations.htm"
df = pd.read_html(filename)[0]

In [3]:
df

,Document,ID,Type,Offset,Length,Text
0,31991541,005,Virus_other,114,8,SARS-CoV
1,31991541,006,Virus_SARS-CoV-2,293,41,most recent emergent group 2B coronavirus
2,31991541,002,Virus_SARS-CoV-2,27,9,2019-nCoV
3,31991541,001,Virus_family,14,11,Coronavirus
4,31991541,003,Virus_SARS-CoV-2,57,17,novel coronavirus
...,...,...,...,...,...,...
194,31996494,A60,Virus_SARS-CoV-2,410,9,2019-nCoV
195,31996494,A61,Virus_family,719,13,coronaviruses
196,31996494,A62,Virus_family,792,26,human pathogen coronavirus
197,31996494,A63,Virus_SARS-CoV-2,1160,9,2019-nCoV
198,31996494,A64,Virus_SARS-CoV-2,1223,10,2019- nCoV

In [4]:
document_ids = set(df["Document"].to_list())
document_ids

{31986264,
 31991541,
 31992388,
 31996494,
 32007643,
 32013309,
 32015508,
 32020836,
 32029004,
 32036774}

In [12]:
for docid in sorted(document_ids):
    print(str(docid) + "\n")
    df_temp = df[df["Document"]== docid]
#     print(df_temp)
    df_temp2 = df_temp[["Document", "Type", "Text"]]
#     print(df_temp2)
    print(df_temp2["Type"].value_counts())
    print(sum(df_temp2["Type"].value_counts()))
    
    print("\n")

31986264

Species_human       17
Symptom             16
Protein              8
Virus_SARS-CoV-2     5
Disease_other        5
Disease_COVID-19     3
Virus_other          1
Name: Type, dtype: int64
55


31991541

Virus_SARS-CoV-2    4
Virus_other         1
Virus_family        1
Name: Type, dtype: int64
6


31992388

Disease_COVID-19    2
Virus_SARS-CoV-2    2
Name: Type, dtype: int64
4


31996494

Virus_SARS-CoV-2    7
Virus_family        3
Name: Type, dtype: int64
10


32007643

Virus_SARS-CoV-2    6
Disease_other       3
Disease_COVID-19    1
Name: Type, dtype: int64
10


32013309

Symptom             7
Virus_family        5
Disease_other       5
Cell                5
Protein             2
Species_human       2
Virus_SARS-CoV-2    1
Chemical            1
Name: Type, dtype: int64
28


32015508

Virus_SARS-CoV-2    5
Disease_other       5
Species_human       5
Symptom             3
Virus_family        3
Disease_COVID-19    2
Species_other       1
Name: Type, dtype: int64
24


32020836

Virus_SARS-CoV-2    5
Virus_family        4
Protein             4
Disease_other       3
Virus_other         3
Species_human       3
Symptom             2
Species_other       2
Name: Type, dtype: int64
26


32029004

Disease_COVID-19    6
Virus_SARS-CoV-2    3
Disease_other       2
Name: Type, dtype: int64
11


32036774

Virus_SARS-CoV-2    10
Virus_other          4
Species_other        4
Virus_family         3
Disease_other        3
Species_human        1
Name: Type, dtype: int64
25